"""Unit tests for ReportClient and _compose_report."""

from unittest.mock import patch

from copilot.clients.report_client import ReportClient, _compose_report


class TestComposeReport:
    def test_twin_state_only(self):
        result = _compose_report(
            "Karnataka",
            "summary",
            {
                "max_temp": 35.0,
                "min_temp": 22.0,
                "rainfall_mm": 10.0,
                "humidity_pct": 65,
                "timestamp": "2026-07-04",
            },
            [],
            {},
        )
        assert "35.0" in result
        assert "22.0" in result
        assert "10.0" in result
        assert "65" in result
        assert "Forecast" not in result
        assert "Risk" not in result

    def test_twin_state_missing_keys(self):
        result = _compose_report("Karnataka", "summary", {}, [], {})
        assert "Current State" not in result

    def test_risk_with_all_fields(self):
        risk = {
            "heat_risk": 45.0,
            "flood_risk": 30.0,
            "drought_risk": 60.0,
            "composite_risk": 45.0,
            "category": "Moderate",
        }
        result = _compose_report("Karnataka", "summary", {}, [], risk)
        assert "45.0" in result
        assert "30.0" in result
        assert "60.0" in result
        assert "Moderate" in result

    def test_risk_partial_data(self):
        risk = {"heat_risk": 50.0}
        result = _compose_report("Karnataka", "summary", {}, [], risk)
        assert "50.0" in result
        assert "Composite" not in result

    def test_risk_no_category(self):
        risk = {"heat_risk": 50.0, "composite_risk": 40.0}
        result = _compose_report("Karnataka", "summary", {}, [], risk)
        assert "Category" not in result

    def test_forecast_for_summary(self):
        forecast = [
            {"day": 1, "max_temp": 35.0, "min_temp": 22.0, "rainfall_mm": 10.0},
            {"day": 2, "max_temp": 34.0, "min_temp": 21.0, "rainfall_mm": 5.0},
        ]
        result = _compose_report("Karnataka", "summary", {}, forecast, {})
        assert "Day 1" in result
        assert "35.0" in result
        assert "Day 2" in result
        assert "34.0" in result

    def test_forecast_for_detailed(self):
        forecast = [{"day": 1, "max_temp": 30.0, "min_temp": 20.0, "rainfall_mm": 0.0}]
        result = _compose_report("Karnataka", "detailed", {}, forecast, {})
        assert "Day 1" in result

    def test_forecast_for_forecast_type(self):
        forecast = [{"day": 1, "max_temp": 30.0, "min_temp": 20.0, "rainfall_mm": 0.0}]
        result = _compose_report("Karnataka", "forecast", {}, forecast, {})
        assert "Day 1" in result

    def test_forecast_not_included_for_risk_type(self):
        forecast = [{"day": 1, "max_temp": 30.0, "min_temp": 20.0, "rainfall_mm": 0.0}]
        result = _compose_report("Karnataka", "risk", {}, forecast, {})
        assert "Forecast" not in result

    def test_empty_forecast_list(self):
        result = _compose_report("Karnataka", "summary", {}, [], {})
        assert "Forecast" not in result

    def test_full_report(self):
        risk = {"heat_risk": 45.0, "composite_risk": 30.0, "category": "Low"}
        forecast = [{"day": 1, "max_temp": 32.0, "min_temp": 20.0, "rainfall_mm": 5.0}]
        result = _compose_report("Mysuru", "summary", {"max_temp": 33.0}, forecast, risk)
        assert "Mysuru" in result
        assert "33.0" in result
        assert "45.0" in result
        assert "Day 1" in result
        assert "Climate Copilot" in result

    def test_compose_report_output_structure(self):
        result = _compose_report("Test", "summary", {}, [], {})
        assert result.startswith("# Climate Report for Test")
        assert result.endswith("*Report generated by Climate Copilot*")


class TestReportClient:
    def setup_method(self):
        self.client = ReportClient()

    def test_generate_report_success(self):
        with (
            patch.object(self.client._twin, "get_current_state", return_value={"max_temp": 35.0}),
            patch.object(
                self.client._forecast, "predict", return_value=[{"day": 1, "max_temp": 32.0}]
            ),
            patch.object(self.client._risk, "assess", return_value={"heat_risk": 30.0}),
        ):
            result = self.client.generate_report("Karnataka")
            assert "35.0" in result
            assert "32.0" in result
            assert "30.0" in result

    def test_twin_client_failure(self):
        with (
            patch.object(
                self.client._twin, "get_current_state", side_effect=Exception("Twin down")
            ),
            patch.object(self.client._forecast, "predict", return_value=[]),
            patch.object(self.client._risk, "assess", return_value={}),
        ):
            result = self.client.generate_report("Karnataka")
            assert "Karnataka" in result

    def test_forecast_client_failure(self):
        with (
            patch.object(self.client._twin, "get_current_state", return_value={}),
            patch.object(self.client._forecast, "predict", side_effect=Exception("Forecast down")),
            patch.object(self.client._risk, "assess", return_value={}),
        ):
            result = self.client.generate_report("Karnataka")
            assert "Karnataka" in result

    def test_risk_client_failure(self):
        with (
            patch.object(self.client._twin, "get_current_state", return_value={}),
            patch.object(self.client._forecast, "predict", return_value=[]),
            patch.object(self.client._risk, "assess", side_effect=Exception("Risk down")),
        ):
            result = self.client.generate_report("Karnataka")
            assert "Karnataka" in result

    def test_all_clients_fail(self):
        with (
            patch.object(
                self.client._twin, "get_current_state", side_effect=ConnectionError("refused")
            ),
            patch.object(self.client._forecast, "predict", side_effect=TimeoutError("timeout")),
            patch.object(self.client._risk, "assess", side_effect=Exception("crashed")),
        ):
            result = self.client.generate_report("Karnataka", "detailed")
            assert "Karnataka" in result

    def test_generate_report_with_different_types(self):
        with (
            patch.object(self.client._twin, "get_current_state", return_value={}),
            patch.object(self.client._forecast, "predict", return_value=[]),
            patch.object(self.client._risk, "assess", return_value={}),
        ):
            for rtype in ("summary", "detailed", "risk", "forecast"):
                result = self.client.generate_report("Karnataka", rtype)
                assert result
                assert rtype in result
