global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "twin-state-mgr"
    static_configs:
      - targets: ["twin-state-mgr:8001"]
  - job_name: "scenario-engine"
    static_configs:
      - targets: ["scenario-engine:8002"]
  - job_name: "risk-engine"
    static_configs:
      - targets: ["risk-engine:8003"]
  - job_name: "rag-service"
    static_configs:
      - targets: ["rag-service:8004"]
  - job_name: "copilot-agent"
    static_configs:
      - targets: ["copilot-agent:8005"]
  - job_name: "forecast-engine"
    static_configs:
      - targets: ["forecast-engine:8006"]
  - job_name: "api-gateway"
    static_configs:
      - targets: ["fastapi-gateway:8000"]
  - job_name: "report-service"
    static_configs:
      - targets: ["twin-report:8007"]
  - job_name: "streamlit-dashboard"
    static_configs:
      - targets: ["streamlit-dashboard:8501"]
  - job_name: "redis"
    static_configs:
      - targets: ["twin-redis:6379"]
