"""Automated summary report generation for scenario simulations."""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any

from simulator.models.scenario_models import ScenarioRun


class ReportGenerator:
    """Generates automated climate impact reports from simulation runs."""

    def __init__(self, output_dir: str = "simulator/reports") -> None:
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_summary(self, run: ScenarioRun) -> dict[str, Any]:
        """Generate a structured summary of the simulation run."""
        agg = self._aggregate_deltas(run)
        return {
            "report_title": f"Climate Impact Report: {run.scenario.name}",
            "run_id": run.run_id,
            "scenario_id": run.scenario.scenario_id,
            "scenario_type": run.scenario.scenario_type,
            "total_locations": run.location_count,
            "successful_locations": sum(1 for r in run.results if r.success),
            "failed_locations": sum(1 for r in run.results if not r.success),
            "duration_ms": run.total_duration_ms,
            "aggregate_deltas": agg,
            "generated_at": datetime.now().isoformat(),
        }

    def generate_markdown_report(self, run: ScenarioRun) -> str:
        """Generate a detailed markdown report."""
        summary = self.generate_summary(run)
        agg = summary["aggregate_deltas"]

        lines = [
            f"# {summary['report_title']}",
            "",
            f"**Generated:** {summary['generated_at']}",
            f"**Scenario:** {run.scenario.name} (`{run.scenario.scenario_id}`)",
            f"**Type:** {run.scenario.scenario_type}",
            "",
            "## Overview",
            "",
            "| Metric | Value |",
            "| --- | --- |",
            f"| Total Locations | {summary['total_locations']} |",
            f"| Successful | {summary['successful_locations']} |",
            f"| Failed | {summary['failed_locations']} |",
            f"| Execution Time | {summary['duration_ms']:.2f}ms |",
            "",
            "## Aggregate Impact",
            "",
            "| Variable | Average (delta) | Min (delta) | Max (delta) |",
            "| --- | --- | --- | --- |",
        ]

        for var, stats in agg.items():
            lines.append(
                f"| {var} | {stats['avg']:+.2f} | {stats['min']:+.2f} | {stats['max']:+.2f} |"
            )

        lines.extend([
            "",
            "## Scenario Parameters",
            "",
            "```json",
            f"{json.dumps(run.scenario.parameters, indent=2)}",
            "```",
            "",
            "## Variable Changes",
            "",
        ])

        for result in run.results:
            if result.success:
                lines.append(
                    f"### {result.location_id}",
                )
                for key, delta in result.deltas.items():
                    b_val = result.baseline.get(key, "N/A")
                    s_val = result.simulated.get(key, "N/A")
                    lines.append(f"- **{key}**: {b_val} → {s_val} ({delta:+.2f})")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by the Scenario Simulation Engine*")

        report = "\n".join(lines)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = os.path.join(
            self.output_dir, f"report_{run.scenario.scenario_id}_{timestamp}.md"
        )
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        return filepath

    @staticmethod
    def _aggregate_deltas(
        run: ScenarioRun,
    ) -> dict[str, dict[str, float]]:
        """Aggregate delta statistics across all results."""
        agg: dict[str, list[float]] = {}
        for result in run.results:
            if not result.success:
                continue
            for key, val in result.deltas.items():
                if key not in agg:
                    agg[key] = []
                agg[key].append(val)

        stats: dict[str, dict[str, float]] = {}
        for var, values in agg.items():
            if values:
                stats[var] = {
                    "avg": round(sum(values) / len(values), 2),
                    "min": round(min(values), 2),
                    "max": round(max(values), 2),
                }
        return stats
