from __future__ import annotations

from typing import Any

from copilot.tools.base import BaseTool


class ReportGeneratorTool(BaseTool):
    def __init__(self) -> None:
        self._name = "report_generator"
        self._description = "Generate a structured climate report combining forecast, risk, and twin state data"

    def run(self, **kwargs: Any) -> dict[str, Any]:
        report_type = kwargs.get("report_type", "summary")
        location = kwargs.get("location", "Karnataka")
        return {"tool": self._name, "report_type": report_type, "location": location, "report": _synthetic_report(location, report_type)}

    def validate(self, **kwargs: Any) -> tuple[bool, str]:
        valid_types = ["summary", "detailed", "risk", "forecast"]
        if "report_type" in kwargs and kwargs["report_type"] not in valid_types:
            return False, f"report_type must be one of {valid_types}"
        if "location" in kwargs and not isinstance(kwargs["location"], str):
            return False, "location must be a string"
        return True, ""

    def describe(self) -> dict[str, Any]:
        return {
            "name": self._name,
            "description": self._description,
            "parameters": {"report_type": "str (summary/detailed/risk/forecast)", "location": "str"},
        }

    def health_check(self) -> tuple[bool, str]:
        return True, "report_generator healthy"


def _synthetic_report(location: str, report_type: str) -> str:
    return f"# Climate Report for {location}\n\n**Report Type:** {report_type}\n\nLocation: {location}\nAverage Temperature: 32.5°C\nAverage Rainfall: 45.2mm\nRisk Level: Moderate\n\n*Generated by Climate Copilot*"
