from __future__ import annotations

import logging
from typing import Any

from copilot.clients.forecast_client import ForecastClient
from copilot.clients.risk_client import RiskClient
from copilot.clients.twin_client import TwinClient

logger = logging.getLogger(__name__)


class ReportClient:
    def __init__(self) -> None:
        self._forecast = ForecastClient()
        self._risk = RiskClient()
        self._twin = TwinClient()

    def generate_report(self, location: str, report_type: str = "summary") -> str:
        try:
            twin_state = self._twin.get_current_state(location)
        except Exception:
            twin_state = {}
            logger.warning("TwinClient unavailable for report, continuing with partial data")

        try:
            forecast = self._forecast.predict(location, days=3)
        except Exception:
            forecast = []
            logger.warning("ForecastClient unavailable for report, continuing with partial data")

        try:
            risk = self._risk.assess(location)
        except Exception:
            risk = {}
            logger.warning("RiskClient unavailable for report, continuing with partial data")

        return _compose_report(location, report_type, twin_state, forecast, risk)


def _compose_report(
    location: str,
    report_type: str,
    twin_state: dict[str, Any],
    forecast: list[dict[str, Any]],
    risk: dict[str, Any],
) -> str:
    lines: list[str] = []
    lines.append(f"# Climate Report for {location}")
    lines.append(f"**Report Type:** {report_type}")
    lines.append("")

    if twin_state:
        lines.append("## Current State")
        lines.append(
            f"- **Temperature:** {twin_state.get('max_temp', 'N/A')}°C / {twin_state.get('min_temp', 'N/A')}°C"
        )
        lines.append(f"- **Rainfall:** {twin_state.get('rainfall_mm', 'N/A')} mm")
        lines.append(f"- **Humidity:** {twin_state.get('humidity_pct', 'N/A')}%")
        lines.append(f"- **Timestamp:** {twin_state.get('timestamp', 'N/A')}")
        lines.append("")

    if risk:
        lines.append("## Risk Assessment")
        for key, label in [
            ("heat_risk", "Heat"),
            ("flood_risk", "Flood"),
            ("drought_risk", "Drought"),
        ]:
            val = risk.get(key)
            if val is not None:
                lines.append(f"- **{label} Risk:** {val:.1f}")
        composite = risk.get("composite_risk")
        if composite is not None:
            lines.append(f"- **Composite Risk:** {composite:.1f}")
        cat = risk.get("category")
        if cat:
            lines.append(f"- **Category:** {cat}")
        lines.append("")

    if forecast and report_type in ("summary", "detailed", "forecast"):
        lines.append("## Forecast (3-Day)")
        for day in forecast:
            lines.append(
                f"- **Day {day.get('day', '?')}:** "
                f"Max {day.get('max_temp', 'N/A')}°C / "
                f"Min {day.get('min_temp', 'N/A')}°C, "
                f"Rainfall {day.get('rainfall_mm', 'N/A')}mm"
            )
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by Climate Copilot*")
    return "\n".join(lines)
